YusanBlogger/Areas/DashboardAreas/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace YusanBlogger.Areas.DashboardAreas.Controllers
{
    public class DashboardController : Controller
    {
        // GET /Dashboard/DashboardIndex/
        [HttpGet]
        public IActionResult DashboardIndex()
        {
            return View();
        }

        // GET /Dashboard/MakeArticles/
        [HttpGet]
        public IActionResult MakeArticles()
        {
            return View();
        }

        // POST Dashboard/MakeArticles/
        [HttpPost]
        public IActionResult MakeArticles(object data)
        {
            return View();
        }

        // GET Dashboard/ArticlesList/
        [HttpGet]
        public IActionResult ArticlesList()
        {
            return View();
        }

        // GET Dashboard/ArticlesList/5
        public IActionResult GetArticles(int? id)
        {
            return View();
        }
    }
}

YusanBlogger/Areas/DashboardAreas/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace YusanBlogger.Areas.DashboardAreas.Controllers
{
    public class MembershipController : Controller
    {
        // GET /Membership/LoginSystem/
        [HttpGet]
        public IActionResult LoginSystem()
        {
            return View();
        }

        // POST /Membership/LoginSystem/Object
        [HttpPost]
        public IActionResult LoginSystem(object data)
        {
            return View();
        }

        // GET /Membership/LoginSystem/
        [HttpGet]
        public IActionResult RegisterSystem()
        {
            return View();
        }

        // POST /Membership/RegisterSystem/Object
        [HttpPost]
        public IActionResult RegisterSystem(object data)
        {
            return View();
        }
    }
}

YusanBlogger/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace YusanBlogger.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DetailPost()
        {
            return View();
        }
    }
}

YusanBlogger/Areas/DashboardAreas/Views/Dashboard/ArticlesList.cshtml
@{
    ViewData["Title"] = "ArticlesList";
}

<h2>Articles List</h2>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <ol class="breadcrumb breadcrumb-bg-teal">
            <li>
                <a asp-area="DashboardAreas" asp-controller="Dashboard" asp-action="DashboardIndex">
                    <i class="material-icons">home</i>
                    <span>Home</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <i class="material-icons">widgets</i>
                    <span>Articles Management</span>
                </a>
            </li>
            <li class="active">
                <a href="javascript:void(0);">
                    <span>Manage Articles</span>
                </a>
            </li>
            <li class="active">
                <a href="javascript:void(0);">
                    <span>Articles List</span>
                </a>
            </li>
        </ol>
    </div>
</div>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Collection of article</h2>
            </div>
            <div class="body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover js-article-list dataTable">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Position</th>
                                <th>Office</th>
                                <th>Age</th>
                                <th>Start date</th>
                                <th>Salary</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Tiger Nixon</td>
                                <td>System Architect</td>
                                <td>Edinburgh</td>
                                <td>61</td>
                                <td>2011/04/25</td>
                                <td>$320,800</td>
                            </tr>
                            <tr>
                                <td>Tiger Nixon</td>
                                <td>System Architect</td>
                                <td>Edinburgh</td>
                                <td>61</td>
                                <td>2011/04/25</td>
                                <td>$320,800</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    
}

YusanBlogger/Areas/DashboardAreas/Views/Dashboard/DashboardIndex.cshtml
@{
    ViewData["Title"] = "DashboardIndex";
    Layout = "~/Areas/DashboardAreas/Views/Shared/_Layout.cshtml";
}

<div class="block-header">
    <h1>YUSAN BLOG DASHBOARD</h1>
</div>
<!-- Widgets -->
<div class="row clearfix">
    <partial name="_PartialWidgets" />
</div>
<!-- #END# Widgets -->
<!-- CPU Usage -->
<div class="row clearfix">
    <partial name="_PartialCPUUsage" />
</div>
<!-- #END# CPU Usage -->
<div class="row clearfix">
    <partial name="_PartialBlogInfo" />
</div>

YusanBlogger/Areas/DashboardAreas/Views/Dashboard/MakeArticles.cshtml
@{
    ViewData["Title"] = "MakeArticles";
}

<h2>Make Your Articles</h2>
<div class="row clearfix">
    <ol class="breadcrumb breadcrumb-bg-teal">
        <li>
            <a asp-area="DashboardAreas" asp-controller="Dashboard" asp-action="DashboardIndex">
                <i class="material-icons">home</i>
                <span>Home</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <i class="material-icons">widgets</i>
                <span>Articles Management</span>
            </a>
        </li>
        <li class="active">
            <a href="javascript:void(0);">
                <i class="material-icons">chat_bubble</i>
                <span>Making Articles</span>
            </a>
        </li>
    </ol>
</div>
<div class="row clearfix">
    <textarea name="CKEditorArticles" id="CKEditorArticles" rows="100" cols="90"></textarea>
</div>

@section Scripts {
    <script type="text/javascript">
        'use strict';
        // Replace the <textarea id="CKEditorArticles"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace('CKEditorArticles', {
            height: '550px',
        });
    </script>
}

YusanBlogger/Areas/DashboardAreas/Views/Membership/LoginSystem.cshtml
@{ 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sign In | Yusan Blogger</title>

    <environment include="Development">
        <!-- Favicon-->
        <link rel="icon" href="~/images/favicon.ico" type="image/x-icon">
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
        <!-- Bootstrap Core Css -->
        <link href="~/plugins/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <!-- Waves Effect Css -->
        <link href="~/plugins/node-waves/waves.css" rel="stylesheet" />
        <!-- Animate Css -->
        <link rel="stylesheet" type="text/css" href="~/plugins/animate-css/animate.min.css" />
        <!-- Custom Css -->
        <link rel="stylesheet" type="text/css" href="~/css/style.css" />
    </environment>
</head>
<body class="login-page">
    <div class="login-box">
        <div class="logo">
            <a href="javascript:void(0);">Yusan Blogger <b>Dashboard</b></a>
            <small>Yusan Blogger - Sign In System</small>
        </div>
        <div class="card">
            <div class="body">
                <form asp-area="DashboardAreas" asp-controller="Membership" asp-action="LoginSystem" id="sign_in" method="POST">
                    <div class="msg">Sign in to start your session</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="username" placeholder="Username" required autofocus>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="password" placeholder="Password" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-8 p-t-5">
                            <input type="checkbox" name="rememberme" id="rememberme" class="filled-in chk-col-pink">
                            <label for="rememberme">Remember Me</label>
                        </div>
                        <div class="col-xs-4">
                            <button class="btn btn-block bg-pink waves-effect" type="submit">SIGN IN</button>
                        </div>
                    </div>
                    <div class="row m-t-15 m-b--20">
                        <div class="col-xs-6">
                            <a asp-area="DashboardAreas" asp-controller="Membership" asp-action="RegisterSystem">Register Now!</a>
                        </div>
                        <div class="col-xs-6 align-right">
                            <a href="#">Forgot Password?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/plugins/jquery-3.3.1/jquery-3.3.1.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-3.3.1/jquery-slim-3.3.1.min.js" asp-append-version="true"></script>
        <script src="~/plugins/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/plugins/node-waves/waves.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-validation/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/js/admin.js" asp-append-version="true"></script>
        <script src="~/js/pages/examples/sign-in.js" asp-append-version="true"></script>
    </environment>
</body>
</html>

YusanBlogger/Areas/DashboardAreas/Views/Membership/RegisterSystem.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sign Up | Yusan Blogger</title>

    <environment include="Development">
        <!-- Favicon-->
        <link rel="icon" href="~/images/favicon.ico" type="image/x-icon">
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
        <!-- Bootstrap Core Css -->
        <link href="~/plugins/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <!-- Waves Effect Css -->
        <link href="~/plugins/node-waves/waves.css" rel="stylesheet" />
        <!-- Animate Css -->
        <link rel="stylesheet" type="text/css" href="~/plugins/animate-css/animate.min.css" />
        <!-- Custom Css -->
        <link rel="stylesheet" type="text/css" href="~/css/style.css" />
    </environment>
</head>
<body class="signup-page">
    <div class="signup-box">
        <div class="logo">
            <a href="javascript:void(0);">Yusan Blogger<b>Dashboard</b></a>
            <small>Yusan Blogger - Sign Up System</small>
        </div>
        <div class="card">
            <div class="body">
                <form asp-area="DashboardAreas" asp-controller="Membership" asp-action="RegisterSystem" id="sign_up" method="POST">
                    <div class="msg">Register a new membership</div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                        <div class="form-line">
                            <input type="text" class="form-control" name="namesurname" placeholder="Name Surname" required autofocus>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">email</i>
                        </span>
                        <div class="form-line">
                            <input type="email" class="form-control" name="email" placeholder="Email Address" required>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="password" minlength="6" placeholder="Password" required>
                        </div>
                    </div>
                    <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                        <div class="form-line">
                            <input type="password" class="form-control" name="confirm" minlength="6" placeholder="Confirm Password" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="checkbox" name="terms" id="terms" class="filled-in chk-col-pink">
                        <label for="terms">I read and agree to the <a href="javascript:void(0);">terms of usage</a>.</label>
                    </div>
                    <button class="btn btn-block btn-lg bg-pink waves-effect" type="submit">SIGN UP</button>
                    <div class="m-t-25 m-b--5 align-center">
                        <a asp-area="DashboardAreas" asp-controller="Membership" asp-action="LoginSystem">You already have a membership?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/plugins/jquery-3.3.1/jquery-3.3.1.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-3.3.1/jquery-slim-3.3.1.min.js" asp-append-version="true"></script>
        <script src="~/plugins/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/plugins/node-waves/waves.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-validation/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/js/admin.js" asp-append-version="true"></script>
        <script src="~/js/pages/examples/sign-up.js" asp-append-version="true"></script>
    </environment>
</body>
</html>

YusanBlogger/Areas/DashboardAreas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Dashboard</title>

    <environment include="Development">
        <!-- Favicon-->
        <link rel="icon" href="~/images/favicon.ico" type="image/x-icon">
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
        <!-- Bootstrap Core Css -->
        <link href="~/plugins/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <!-- CKEditor4 -->
        <link href="~/plugins/ckeditor/contents.css" rel="stylesheet" />
        <!-- Waves Effect Css -->
        <link href="~/plugins/node-waves/waves.css" rel="stylesheet" />
        <!-- Animate Css -->
        <link rel="stylesheet" type="text/css" href="~/plugins/animate-css/animate.min.css" />
        <!-- Animation Css -->
        <link href="~/plugins/animate-css/animate.css" rel="stylesheet" />
        <!-- Morris Chart Css-->
        <link href="~/plugins/morrisjs/morris.css" rel="stylesheet" />
        <!-- Custom Css -->
        <link href="~/css/style.css" rel="stylesheet" />
        <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
        <link href="~/css/themes/all-themes.css" rel="stylesheet" />
        <!-- JQuery Datatables Css -->
        <link href="~/plugins/jquery-datatable/DataTables-1.10.18/css/dataTables.bootstrap.css" rel="stylesheet" />
    </environment>
</head>
<body class="theme-teal">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-pink">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->
    <div class="search-bar">
        <div class="search-icon">
            <i class="material-icons">search</i>
        </div>
        <input type="text" placeholder="START TYPING...">
        <div class="close-search">
            <i class="material-icons">close</i>
        </div>
    </div>
    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    <nav class="navbar">
        <div class="container-fluid">
            <partial name="_PartialTopBarMenu" />
        </div>
    </nav>
    <!-- #Top Bar -->
    <section>
        <!-- Left Sidebar -->
        <partial name="_PartialLeftSidebar" />
        <!-- #END# Left Sidebar -->
        <!-- Right Sidebar -->
        <partial name="_PartialRightSidebar" />
        <!-- #END# Right Sidebar -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <!-- Content Body -->
            @RenderBody()
            <!-- #END# Content Body -->
        </div>
    </section>

    <environment include="Development">
        <!-- CKEditor4 -->
        <script src="~/plugins/ckeditor/ckeditor.js" asp-append-version="true"></script>
        <!-- Jquery Core Js -->
        <script src="~/plugins/jquery-3.3.1/jquery-3.3.1.min.js" asp-append-version="true"></script>
        <!-- Bootstrap Core Js -->
        <script src="~/plugins/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>
        <!-- Select Plugin Js -->
        <script src="~/plugins/bootstrap-select/js/bootstrap-select.min.js" asp-append-version="true"></script>
        <!-- Slimscroll Plugin Js -->
        <script src="~/plugins/jquery-slimscroll/jquery.slimscroll.js" asp-append-version="true"></script>
        <!-- Waves Effect Plugin Js -->
        <script src="~/plugins/node-waves/waves.min.js" asp-append-version="true"></script>
        <!-- Jquery CountTo Plugin Js -->
        <script src="~/plugins/jquery-countto/jquery.countTo.js" asp-append-version="true"></script>
        <!-- Morris Plugin Js -->
        <script src="~/plugins/raphael/raphael.min.js" asp-append-version="true"></script>
        <script src="~/plugins/morrisjs/morris.min.js" asp-append-version="true"></script>
        <!-- ChartJs -->
        <script src="~/plugins/chartjs/Chart.bundle.min.js" asp-append-version="true"></script>
        <!-- Flot Charts Plugin Js -->
        <script src="~/plugins/flot-charts/jquery.flot.js" asp-append-version="true"></script>
        <script src="~/plugins/flot-charts/jquery.flot.resize.js" asp-append-version="true"></script>
        <script src="~/plugins/flot-charts/jquery.flot.pie.js" asp-append-version="true"></script>
        <script src="~/plugins/flot-charts/jquery.flot.categories.js" asp-append-version="true"></script>
        <script src="~/plugins/flot-charts/jquery.flot.time.js" asp-append-version="true"></script>
        <!-- Sparkline Chart Plugin Js -->
        <script src="~/plugins/jquery-sparkline/jquery.sparkline.js" asp-append-version="true"></script>
        <!-- JQuery DataTable Script -->
        @*<script src="~/plugins/jquery-datatable/jQuery-1.12.4/jquery-1.12.4.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/DataTables-1.10.18/js/jquery.dataTables.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/DataTables-1.10.18/js/dataTables.bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/Buttons-1.5.6/js/dataTables.buttons.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/Buttons-1.5.6/js/buttons.flash.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/JSZip-2.5.0/jszip.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/pdfmake-0.1.36/pdfmake.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/pdfmake-0.1.36/vfs_fonts.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/Buttons-1.5.6/js/buttons.html5.min.js" asp-append-version="true"></script>
        <script src="~/plugins/jquery-datatable/Buttons-1.5.6/js/buttons.print.min.js" asp-append-version="true"></script>
        <script src="~/js/pages/tables/jquery-datatable.js" asp-append-version="true"></script>*@
        <!-- Use SignalR Library -->
        <script src="~/js/dist/browser/signalr.min.js" asp-append-version="true"></script>
        <!-- Custom Js -->
        <script src="~/js/admin.js" asp-append-version="true"></script>
        <script src="~/js/pages/index.js" asp-append-version="true"></script>
        <!-- Demo Js -->
        <script src="~/js/demo.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

YusanBlogger/Areas/DashboardAreas/Views/Shared/_PartialLeftSidebar.cshtml
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        <div class="image">
            <img src="~/images/user.png" width="48" height="48" alt="User" />
        </div>
        <div class="info-container">
            <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">John Doe</div>
            <div class="email">john.doe@example.com</div>
            <div class="btn-group user-helper-dropdown">
                <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                <ul class="dropdown-menu pull-right">
                    <li><a href="javascript:void(0);"><i class="material-icons">account_circle</i>Profile</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="javascript:void(0);"><i class="material-icons">favorite</i>Likes</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="javascript:void(0);"><i class="material-icons">input</i>Sign Out</a></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- #User Info -->
    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active">
                <a asp-area="DashboardAreas" asp-controller="Dashboard" asp-action="DashboardIndex">
                    <i class="material-icons">home</i>
                    <span>Home</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);" class="menu-toggle">
                    <i class="material-icons">widgets</i>
                    <span>Articles Management</span>
                </a>
                <ul class="ml-menu">
                    <li>
                        <a asp-area="DashboardAreas" asp-controller="Dashboard" asp-action="MakeArticles">
                            <i class="material-icons">chat_bubble</i>
                            <span>Making Articles</span>
                        </a>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="menu-toggle">
                            <span>Manage Articles</span>
                        </a>
                        <ul class="ml-menu">
                            <li>
                                <a asp-area="DashboardAreas" asp-controller="Dashboard" asp-action="ArticlesList">Articles List</a>
                            </li>
                            <li>
                                <a href="#">Update Articles</a>
                            </li>
                            <li>
                                <a href="#">Remove Articles</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:void(0);" class="menu-toggle">
                    <i class="material-icons">people</i>
                    <span>Users Management</span>
                </a>
                <ul class="ml-menu">
                    <li>
                        <a >
                            <i class="material-icons">person</i>
                            <span>Create User</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">Users List</a>
                    </li>
                    <li>
                        <a href="#">Update Users</a>
                    </li>
                    <li>
                        <a href="#">Remove Users</a>
                    </li>
                </ul>
            </li>
            <li class="header">LABELS</li>
            <li>
                <a href="javascript:void(0);">
                    <i class="material-icons col-red">donut_large</i>
                    <span>Important</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <i class="material-icons col-amber">donut_large</i>
                    <span>Warning</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0);">
                    <i class="material-icons col-light-blue">donut_large</i>
                    <span>Information</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- #Menu -->
    <!-- Footer -->
    <div class="legal">
        <div class="copyright">
            &copy; @DateTime.Now.Year <a href="javascript:void(0);">YUSAN BLOGGER</a>.
        </div>
        <div class="version">
            <b>Priview Version </b> @*1.0.0*@
        </div>
    </div>
    <!-- #Footer -->
</aside>

YusanBlogger/Areas/DashboardAreas/Views/Shared/_PartialTopBarMenu.cshtml
<div class="navbar-header">
    <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
    <a href="javascript:void(0);" class="bars"></a>
    <a asp-area="DashboardAreas" asp-controller="Dashboard" asp-action="DashboardIndex" class="navbar-brand">YUSAN - ADMIN DASHBOARD</a>
</div>
<div class="collapse navbar-collapse" id="navbar-collapse">
    <ul class="nav navbar-nav navbar-right">
        <!-- Call Search -->
        <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>
        <!-- #END# Call Search -->
        <!-- Notifications -->
        <li class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                <i class="material-icons">notifications</i>
                <span class="label-count">1</span>
            </a>
            <ul class="dropdown-menu">
                <li class="header">NOTIFICATIONS</li>
                <li class="body">
                    <ul class="menu">
                        <li>
                            <a href="javascript:void(0);">
                                <div class="icon-circle bg-light-green">
                                    <i class="material-icons">person_add</i>
                                </div>
                                <div class="menu-info">
                                    <h4>12 new members joined</h4>
                                    <p>
                                        <i class="material-icons">access_time</i> 14 mins ago
                                    </p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);">
                                <div class="icon-circle bg-cyan">
                                    <i class="material-icons">add_shopping_cart</i>
                                </div>
                                <div class="menu-info">
                                    <h4>4 sales made</h4>
                                    <p>
                                        <i class="material-icons">access_time</i> 22 mins ago
                                    </p>
                                </div>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="footer">
                    <a href="javascript:void(0);">View All Notifications</a>
                </li>
            </ul>
        </li>
        <!-- #END# Notifications -->
        <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">more_vert</i></a></li>
    </ul>
</div>

YusanBlogger/Views/Shared/_NavBar.cshtml
<ul class="links">
    <li>
        <a href="#">Home</a>
    </li>
    <li>
        <a href="#">Landing</a>
    </li>
    <li>
        <a href="#">Generic</a>
    </li>
    <li>
        <a href="#">Elements</a>
    </li>
</ul>